name: CI/CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Ø³Ø­Ø¨ Ø§Ù„ÙƒÙˆØ¯ Ù…Ù† Ø§Ù„Ø±ÙŠØ¨Ùˆ
      - name: Checkout code
        uses: actions/checkout@v3

      # ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¹Ù„Ù‰ Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker Image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

      # Deploy Ø¹Ù„Ù‰ EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "ğŸ›‘ Stopping and removing old container if exists..."
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^movie-reco\$"; then
              sudo docker stop movie-reco || true
              sudo docker rm movie-reco || true
            fi

            echo "ğŸ³ Pulling latest image from Docker Hub..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

            echo "ğŸš€ Running new container on network movie-network..."
            sudo docker run -d \
              --name movie-reco \
              --network movie-network \
              -p 8000:8000 \
              -p 8501:8501 \
              --memory=4g \
              --cpus="2" \
              ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

            echo "âœ… Deployment successful!"