name: CI/CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # Ø­Ø°Ù Ø£ÙŠ container Ù‚Ø¯ÙŠÙ…
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^movie-reco\$"; then
              echo "ğŸ›‘ Stopping old container..."
              sudo docker stop movie-reco || true
              sudo docker rm movie-reco || true
            fi

            # Ø¹Ù…Ù„ pull Ù„Ù„Ù€ image Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©
            echo "ğŸ³ Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

            # ØªØ´ØºÙŠÙ„ Ø§Ù„Ù€ container Ø§Ù„Ø¬Ø¯ÙŠØ¯ Ø¹Ù„Ù‰ Ù†ÙØ³ Ø§Ù„Ù€ network
            echo "ğŸš€ Running new container on network movie-network..."
            sudo docker run -d \
              --name movie-reco \
              --network movie-network \
              -p 8000:8000 \
              -p 8501:8501 \
              --memory=4g \
              --cpus="2" \
              ${{ secrets.DOCKER_USERNAME }}/movie-reco:latest

            echo "âœ… Deployment successful!"